repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      args: ["--safe", "--quiet", "--line-length", "80"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-docstrings==1.5.0

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
