repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        args: [ "--whitespaces-count", "4" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [
            "--profile", "black",
            "--line-length", "80"
        ]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [
          "--safe",
          "--quiet",
          "--line-length", "80"
      ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [
            "--max-line-length", "80",
            "--extend-ignore", "D205,D212,D415,E203",
            "--exclude", ".eggs,.git,__pycache__,.tox,.vscode,build/,dist/",
            "--docstring-convention", "google"
        ]
        language_version: python3
        additional_dependencies:
          - flake8-docstrings==1.5.0

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check
        args: [
            "--skip", "B404,B603",
            "pyprint.py"
        ]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
        args: [
          "--line-length", "80"
        ]
